#!bin/sh
# Update mirrors
sudo pacman-mirrors --country Sweden,Norway,Germany,Finland && sudo pacman Syyu
# Installs
sudo pacman -S git i3-gaps i3status dmenu zsh fzf autotiling arandr zsh-syntax-highlighting nodejs npm feh compton neovim github-cli tk xclip ripgrep maim
# For alacritty
sudo pacman -S  gcc cmake freetype2 fontconfig pkg-config make libxcb libxkbcommon python
sudo pacman -Fy gitk
# Install-scripts
# sh install-alacritty
sh install-vimplug
sh install-ohmyzsh

# Make directories, symlinks etc
sh dirs
sh symlinks

# Git
sh git-settings

echo "Install of loveh config finished."
echo "Alacritty script is not finished yet, so run that manually and fix any problems by hand."
echo "After that, you can just start vim, do pluginstall, restart computer and enjoy!"
